### PR TITLE
Add a Haskell program

### PR DESCRIPTION
**Pull request by Eleuthere**

### CODE REVIEW

**Review by AntoineKopij — COMMENTED** [review]
Hi Eleuthere, whould you be kind enough to explain where this list comes from in the description, with the right links and references ?

**Comment by Eleuthere** [comment]
The added program selects the records whose last two characters are the 2 letters ISO code of some list of countries.
The list is temporarily hard-coded in the program. The idea in the future is to tell the program what list to consider, and the program will then load it.

**Comment by Eleuthere** [comment]
The list comes from the Oxfam website.

**Comment by Eleuthere** [comment]
https://www.oxfam.org/en/full-disclosure-eus-blacklist-tax-havens
https://oxfam.box.com/s/ttb2dbzabrbzxld8en2x5rekbgflmh34

**Comment by AntoineKopij** [comment]
Thanks a lot!

**Review by AntoineKopij — APPROVED** [review]
I approve the commit but I have to state that I don't know Haskell and that the code needs to be documented.

**Comment by Eleuthere** [comment]
Of course.

The comments are already written. It’s just that I am again trying to bring there changes to GitHub.  :-(

Jean Marie Falisse
Avenue des Naïades, 19/2
B 1170 Watermael-Boitsfort
Belgique
+32 2 673 32 22
+32 479 509899
jmfalisse@acm.org
http://member.acm.org/~jmfalisse

**Pull request merged**
